1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Print the numpy version and the configuration

In [2]:
import numpy as np

# Print version
print("NumPy version:", np.__version__)

# Print full configuration
np.show_config()


NumPy version: 2.2.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-_1vgc7re/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/includ

c:\Users\windo\conda environment\conda2\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


3. Create a null vector of size 10 

In [3]:
import numpy as np

null_vector = np.zeros(10)
print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array

In [4]:
import numpy as np

# Example array
arr = np.zeros((5, 5))

# Memory size in bytes
print("Memory size:", arr.nbytes, "bytes")


Memory size: 200 bytes


5. How to get the documentation of the numpy add function from the command line?

In [5]:
import numpy as np
help(np.add)


Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

6. Create a null vector of size 10 but the fifth value which is 1

In [6]:
import numpy as np

vec = np.zeros(10)   # null vector of size 10
vec[4] = 1           # set the 5th element (index 4) to 1
print(vec)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49

In [7]:
import numpy as np

vec = np.arange(10, 50)
print(vec)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)

In [8]:
import numpy as np

vec = np.arange(10, 50)   # example vector 10 → 49
reversed_vec = vec[::-1]  # reverse the order
print(reversed_vec)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [1]:
[[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8]]


[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [2]:
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)[0]
print(indices)  # Output: [0 1 4]


[0 1 4]


11. Create a 3x3 identity matrix

In [3]:
[[1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]


[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

12. Create a 3x3x3 array with random values

In [4]:
import numpy as np

random_array = np.random.rand(3, 3, 3)
print(random_array)


[[[0.26483212 0.43178395 0.17063617]
  [0.77421345 0.82926098 0.88158278]
  [0.98950344 0.11204383 0.19907749]]

 [[0.35370924 0.95117899 0.76705359]
  [0.95172905 0.69052937 0.35158543]
  [0.47123165 0.50868232 0.87256041]]

 [[0.23004888 0.7638194  0.7169396 ]
  [0.67357945 0.55005758 0.77402921]
  [0.85322442 0.16620724 0.01438502]]]


13. Create a 10x10 array with random values and find the minimum and maximum values

In [5]:
import numpy as np

# Create a 10x10 array with random values between 0 and 1
array = np.random.rand(10, 10)

# Find the minimum and maximum values
min_val = np.min(array)
max_val = np.max(array)

print("Random 10x10 Array:\n", array)
print("\nMinimum Value:", min_val)
print("Maximum Value:", max_val)


Random 10x10 Array:
 [[0.50773607 0.54280654 0.01899367 0.28823974 0.72292194 0.52437085
  0.4759569  0.92004427 0.61833792 0.49900628]
 [0.38489345 0.91223228 0.31312846 0.2019496  0.65763196 0.37367298
  0.96343122 0.03219399 0.77636737 0.57959396]
 [0.69298114 0.0532208  0.47696653 0.06362901 0.3294282  0.84890519
  0.9469143  0.53985417 0.61488584 0.75867687]
 [0.369911   0.25822007 0.69175109 0.64027539 0.74627986 0.11355513
  0.82493551 0.45295981 0.83809853 0.02860292]
 [0.12100468 0.44171614 0.96680494 0.95932647 0.03548897 0.23159813
  0.15881609 0.09596344 0.1366256  0.79834229]
 [0.98110122 0.36236278 0.21408593 0.44115655 0.5784389  0.33986833
  0.41865232 0.08953067 0.17932202 0.18276057]
 [0.93790975 0.66444452 0.45655528 0.34430179 0.51684366 0.77855624
  0.01789613 0.53318103 0.78549513 0.31255981]
 [0.43206336 0.62742649 0.91372671 0.67346089 0.53946879 0.33367602
  0.09647886 0.4617906  0.05802724 0.11525253]
 [0.71760014 0.36211264 0.73446135 0.98733025 0.965733   0.

14. Create a random vector of size 30 and find the mean value

In [6]:
import numpy as np

# Create a random vector of size 30
vector = np.random.rand(30)

# Calculate the mean value
mean_value = np.mean(vector)

print("Random Vector:\n", vector)
print("\nMean Value:", mean_value)


Random Vector:
 [0.5328185  0.65901378 0.88225044 0.28256222 0.18722699 0.10401084
 0.03769063 0.07847208 0.83590768 0.4593244  0.46112571 0.52048179
 0.29488789 0.17390917 0.36676766 0.46425058 0.67350823 0.46300113
 0.45338871 0.91402317 0.34553809 0.68770544 0.50737104 0.86884373
 0.39893386 0.04462892 0.73819345 0.0439385  0.88965221 0.06376598]

Mean Value: 0.44777309459091935


15. Create a 2d array with 1 on the border and 0 inside

In [7]:
import numpy as np

# Create a 5x5 array filled with ones
array = np.ones((5, 5), dtype=int)

# Set the inner part to zeros
array[1:-1, 1:-1] = 0

print(array)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


16. How to add a border (filled with 0's) around an existing array?

In [9]:
import numpy as np

# Original array
array = np.ones((3, 3), dtype=int)

# Add a border of 0s
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)

print(bordered_array)


[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [11]:
# Explanation of each expression:

# 1. 0 * np.nan
# Any operation with np.nan results in np.nan, so this will output nan.
print("0 * np.nan:", 0 * np.nan)  # Output: nan

# 2. np.nan == np.nan
# np.nan is not equal to anything, even itself, so this will output False.
print("np.nan == np.nan:", np.nan == np.nan)  # Output: False

# 3. np.inf > np.nan
# Comparisons with np.nan always return False.
print("np.inf > np.nan:", np.inf > np.nan)  # Output: False

# 4. np.nan - np.nan
# Any arithmetic operation with np.nan results in np.nan.
print("np.nan - np.nan:", np.nan - np.nan)  # Output: nan

# 5. np.nan in set([np.nan])
# np.nan is not equal to itself, but 'in' checks for object identity in sets, so this will output True.
print("np.nan in set([np.nan]):", np.nan in set([np.nan]))  # Output: True

# 6. 0.3 == 3 * 0.1
# Due to floating point precision, this may be False.
print("0.3 == 3 * 0.1:", 0.3 == 3 * 0.1)  # Output: False

0 * np.nan: nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan: nan
np.nan in set([np.nan]): True
0.3 == 3 * 0.1: False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [12]:
import numpy as np

# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
matrix = np.diag([1, 2, 3, 4], k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [13]:
import numpy as np

# Create an 8x8 matrix of zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill with checkerboard pattern
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [14]:
import numpy as np

# For a (6,7,8) array, find the index of the 100th element (0-based indexing)
shape = (6, 7, 8)
element_number = 100  # 0-based index

index = np.unravel_index(element_number, shape)
print("The index (x, y, z) of the 100th element is:", index)

The index (x, y, z) of the 100th element is: (np.int64(1), np.int64(5), np.int64(4))


21. Create a checkerboard 8x8 matrix using the tile function

In [15]:
import numpy as np

# Create a 2x2 checkerboard pattern
pattern = np.array([[0, 1], [1, 0]])

# Tile the pattern to create an 8x8 checkerboard matrix
checkerboard_tile = np.tile(pattern, (4, 4))

print(checkerboard_tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. Normalize a 5x5 random matrix

In [16]:
# Create a 5x5 random matrix
matrix_5x5 = np.random.rand(5, 5)

# Normalize the matrix: (matrix - min) / (max - min)
normalized_matrix = (matrix_5x5 - np.min(matrix_5x5)) / (np.max(matrix_5x5) - np.min(matrix_5x5))

print("Original 5x5 Matrix:\n", matrix_5x5)
print("\nNormalized 5x5 Matrix:\n", normalized_matrix)

Original 5x5 Matrix:
 [[0.61947916 0.97157504 0.42594756 0.97823909 0.0328954 ]
 [0.44458464 0.69697491 0.32421828 0.40968438 0.83984602]
 [0.19123355 0.7092098  0.79321732 0.66494822 0.57952324]
 [0.49451993 0.02700385 0.68921349 0.984886   0.63964489]
 [0.1500419  0.98937482 0.71481855 0.69234379 0.3315225 ]]

Normalized 5x5 Matrix:
 [[0.61564129 0.98150424 0.41454254 0.98842886 0.00612191]
 [0.43390835 0.69616715 0.30883562 0.39764346 0.84462457]
 [0.17065114 0.70888044 0.79617268 0.66288821 0.57412308]
 [0.48579611 0.         0.68810226 0.99533567 0.63659551]
 [0.12784888 1.         0.71470849 0.69135495 0.31642543]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [17]:
import numpy as np

# Define a custom dtype for RGBA color (4 unsigned bytes)
rgba_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])

# Example usage: create an array of colors
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 128), (0, 0, 255, 64)], dtype=rgba_dtype)
print(colors)

[(255,   0,   0, 255) (  0, 255,   0, 128) (  0,   0, 255,  64)]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [18]:
# Create a 5x3 matrix and a 3x2 matrix with random values
A = np.random.rand(5, 3)
B = np.random.rand(3, 2)

# Perform real matrix multiplication
result = np.dot(A, B)

print("5x3 Matrix (A):\n", A)
print("\n3x2 Matrix (B):\n", B)
print("\nResult of A x B:\n", result)

5x3 Matrix (A):
 [[0.80804794 0.92640514 0.70535978]
 [0.16343572 0.98976003 0.87643319]
 [0.57268519 0.05509772 0.04336532]
 [0.77191946 0.16104094 0.80754164]
 [0.93396861 0.40691856 0.85046255]]

3x2 Matrix (B):
 [[0.94627724 0.73531464]
 [0.22187938 0.32085671]
 [0.35177227 0.52855005]]

Result of A x B:
 [[1.21831358 1.26423072]
 [0.68256773 0.90098662]
 [0.56939872 0.46170301]
 [1.05025223 1.04610091]
 [1.27324921 1.26683535]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place

In [19]:
import numpy as np

# Example 1D array
arr1d = np.array([1, 4, 6, 9, 2, 7, 10])

# Negate all elements between 3 and 8 (inclusive of 3 and 8)
arr1d[(arr1d > 3) & (arr1d < 8)] *= -1

print(arr1d)

[ 1 -4 -6  9  2 -7 10]


26. What is the output of the following script?
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [20]:
from numpy import *

# Output of the script:

print(sum(range(5), -1))        # Built-in sum: sum([0,1,2,3,4], -1) = 10 + (-1) = 9

print(sum(range(5), -1))        # numpy sum: sum([0,1,2,3,4], axis=-1) = [0,1,2,3,4] (no axis to sum over), so returns 10

# So the output will be:
# 9
# 10

10
10


27. Consider an integer vector Z, which of these expressions are legal? 

In [22]:
# Check which of the following expressions are legal for the integer vector Z

# 1. Z**Z
expr1 = Z**Z  # Legal: element-wise power

# 2. 2 << Z >> 2
expr2 = 2 << Z >> 2  # Legal: bitwise shift operations

# 3. Z <- Z
# Not legal in Python, '<-' is not an assignment or comparison operator

# 4. 1j*Z
expr4 = 1j * Z  # Legal: multiplies each element by imaginary unit

# 5. Z/1/1
expr5 = Z / 1 / 1  # Legal: element-wise division

# 6. Z<Z>Z
# Not legal in Python, chained comparison must be like (Z < Z) & (Z > Z), but Z<Z>Z is invalid syntax

print("Z**Z:", expr1)
print("2 << Z >> 2:", expr2)
print("1j*Z:", expr4)
print("Z/1/1:", expr5)

Z**Z: [        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
2 << Z >> 2: [  0   1   2   4   8  16  32  64 128 256]
1j*Z: [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
Z/1/1: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


28. What are the result of the following expressions? 

In [23]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\windo\AppData\Local\Temp\ipykernel_16428\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\windo\AppData\Local\Temp\ipykernel_16428\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\windo\AppData\Local\Temp\ipykernel_16428\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


29. How to round away from zero a float array ?

In [24]:
# To round away from zero, use np.copysign and np.ceil on the absolute values
float_array = np.array([-1.7, -0.2, 0.2, 1.7, 2.5, -2.5])

rounded_away = np.copysign(np.ceil(np.abs(float_array)), float_array)
print(rounded_away)

[-2. -1.  1.  2.  3. -3.]


30. How to find common values between two arrays?

In [25]:
# To find common values between two arrays, use np.intersect1d
array1 = np.array([1, 2, 3, 4])
array2 = np.array([3, 4, 5, 6])

common_values = np.intersect1d(array1, array2)
print(common_values)

[3 4]


31. How to ignore all numpy warnings (not recommended)?

In [26]:
import warnings

warnings.filterwarnings('ignore')

32. Is the following expressions true?

In [27]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


33. How to get the dates of yesterday, today and tomorrow?

In [28]:
import numpy as np

today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2025-09-08
Today: 2025-09-09
Tomorrow: 2025-09-10


34. How to get all the dates corresponding to the month of July 2016?

In [29]:
# Get all dates for July 2016
july_2016 = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)?

36. Extract the integer part of a random array of positive numbers using 4 different methods 

In [32]:
# Generate a random array of positive numbers
rand_arr = np.random.uniform(0, 10, 10)
print("Original array:", rand_arr)

# Method 1: Using np.floor
int_part1 = np.floor(rand_arr)
print("Using np.floor:", int_part1)

# Method 2: Using np.trunc
int_part2 = np.trunc(rand_arr)
print("Using np.trunc:", int_part2)

# Method 3: Using astype(int)
int_part3 = rand_arr.astype(int)
print("Using astype(int):", int_part3)

# Method 4: Using np.modf (returns fractional and integer parts)
frac_part, int_part4 = np.modf(rand_arr)
print("Using np.modf:", int_part4)

Original array: [1.67523591 1.52284164 5.33590738 7.94404486 8.81411395 3.42571807
 7.65019759 9.24998066 2.17817364 5.30721294]
Using np.floor: [1. 1. 5. 7. 8. 3. 7. 9. 2. 5.]
Using np.trunc: [1. 1. 5. 7. 8. 3. 7. 9. 2. 5.]
Using astype(int): [1 1 5 7 8 3 7 9 2 5]
Using np.modf: [1. 1. 5. 7. 8. 3. 7. 9. 2. 5.]


37. Create a 5x5 matrix with row values ranging from 0 to 4

In [33]:
# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


38. Consider a generator function that generates 10 integers and use it to build an array

In [34]:
# Define a generator function that yields 10 integers (e.g., 0 to 9)
def gen_10_integers():
    for i in range(10):
        yield i

# Use the generator to build a numpy array
arr_from_gen = np.fromiter(gen_10_integers(), dtype=int)
print(arr_from_gen)

[0 1 2 3 4 5 6 7 8 9]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [35]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
vec = np.linspace(0, 1, 12)[1:-1]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it

In [36]:
# Create a random vector of size 10
random_vec = np.random.rand(10)

# Sort the vector
sorted_vec = np.sort(random_vec)

print("Random Vector:", random_vec)
print("Sorted Vector:", sorted_vec)

Random Vector: [0.87819936 0.1000688  0.91736074 0.76569017 0.39757875 0.9396758
 0.3807288  0.42536893 0.16583305 0.34308523]
Sorted Vector: [0.1000688  0.16583305 0.34308523 0.3807288  0.39757875 0.42536893
 0.76569017 0.87819936 0.91736074 0.9396758 ]


41. How to sum a small array faster than np.sum?

In [37]:
# For small arrays, Python's built-in sum() is often faster than np.sum()
small_array = np.arange(10)
fast_sum = sum(small_array)
print(fast_sum)

45


42. Consider two random array A and B, check if they are equal

In [38]:
# Check if arrays A and B are equal in shape and elements
are_equal = np.array_equal(A, B)
print("Are A and B equal?", are_equal)

Are A and B equal? False


43. Make an array immutable (read-only)

In [39]:
# Make an array immutable (read-only)
arr_readonly = A.copy()
arr_readonly.flags.writeable = False
print("Is array writeable?", arr_readonly.flags.writeable)

Is array writeable? False


44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [40]:
# Assume coords is a random 10x2 matrix representing cartesian coordinates
coords = np.random.rand(10, 2)

# Convert to polar coordinates
r = np.hypot(coords[:, 0], coords[:, 1])
theta = np.arctan2(coords[:, 1], coords[:, 0])

print("Cartesian coordinates:\n", coords)
print("\nPolar coordinates (r, theta):")
for radius, angle in zip(r, theta):
    print(f"r={radius:.4f}, theta={angle:.4f}")

Cartesian coordinates:
 [[0.38223398 0.70232493]
 [0.9638341  0.9228876 ]
 [0.63525677 0.26466418]
 [0.57283334 0.86749327]
 [0.43208466 0.03794505]
 [0.95578591 0.85254853]
 [0.25784416 0.55066176]
 [0.04335872 0.87737829]
 [0.09937545 0.22367133]
 [0.86335008 0.77496052]]

Polar coordinates (r, theta):
r=0.7996, theta=1.0724
r=1.3344, theta=0.7637
r=0.6882, theta=0.3948
r=1.0396, theta=0.9872
r=0.4337, theta=0.0876
r=1.2808, theta=0.7284
r=0.6080, theta=1.1329
r=0.8784, theta=1.5214
r=0.2448, theta=1.1527
r=1.1601, theta=0.7315


Create random vector of size 10 and replace the maximum value by 0

In [41]:
# Create a random vector of size 10
vec10 = np.random.rand(10)

# Replace the maximum value by 0
vec10[vec10.argmax()] = 0

print(vec10)

[0.47491514 0.         0.56920467 0.56863461 0.14000625 0.66435624
 0.55510149 0.75145026 0.5979418  0.02322197]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [42]:
# Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
x = np.linspace(0, 1, 5)
y = np.linspace(0, 1, 5)
grid = np.meshgrid(x, y)
coords_struct = np.zeros(25, dtype=[('x', float), ('y', float)])
coords_struct['x'] = grid[0].ravel()
coords_struct['y'] = grid[1].ravel()
print(coords_struct)

[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [43]:
# Assume X and Y are 1D numpy arrays
X = np.array([0, 1, 2, 3, 4])
Y = np.array([5, 6, 7, 8, 9])

# Construct the Cauchy matrix: C[i, j] = 1 / (X[i] - Y[j])
C = 1.0 / (X[:, None] - Y[None, :])
print(C)

[[-0.2        -0.16666667 -0.14285714 -0.125      -0.11111111]
 [-0.25       -0.2        -0.16666667 -0.14285714 -0.125     ]
 [-0.33333333 -0.25       -0.2        -0.16666667 -0.14285714]
 [-0.5        -0.33333333 -0.25       -0.2        -0.16666667]
 [-1.         -0.5        -0.33333333 -0.25       -0.2       ]]


48. Print the minimum and maximum representable value for each numpy scalar type

In [44]:
# Print the minimum and maximum representable value for each numpy scalar type
for t in ScalarType:
    try:
        info = np.iinfo(t)
        print(f"{t.__name__}: min={info.min}, max={info.max}")
    except (ValueError, TypeError):
        try:
            info = np.finfo(t)
            print(f"{t.__name__}: min={info.min}, max={info.max}")
        except (ValueError, TypeError):
            print(f"{t.__name__}: not a numeric type with min/max")

int: min=-9223372036854775808, max=9223372036854775807
float: min=-1.7976931348623157e+308, max=1.7976931348623157e+308
complex: min=-1.7976931348623157e+308, max=1.7976931348623157e+308
bool: not a numeric type with min/max
bytes: not a numeric type with min/max
str: not a numeric type with min/max
memoryview: not a numeric type with min/max
bool: not a numeric type with min/max
complex64: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
complex128: min=-1.7976931348623157e+308, max=1.7976931348623157e+308
clongdouble: min=-1.7976931348623157e+308, max=1.7976931348623157e+308
float16: min=-65504.0, max=65504.0
float32: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
float64: min=-1.7976931348623157e+308, max=1.7976931348623157e+308
longdouble: min=-1.7976931348623157e+308, max=1.7976931348623157e+308
int8: min=-128, max=127
int16: min=-32768, max=32767
intc: min=-2147483648, max=2147483647
int32: min=-2147483648, max=2147483647
int64: min=-9223372036854775808, max=92233

49. How to print all the values of an array?

50. How to find the closest value (to a given scalar) in a vector? 

In [46]:
# Given a vector and a scalar value, find the closest value in the vector to the scalar
scalar = 0.5  # example scalar
closest_value = vector[np.abs(vector - scalar).argmin()]
print("Closest value to", scalar, "is", closest_value)

Closest value to 0.5 is 0.5073710415757111
